### ISSUE TITLE
Minor mistakes in Chapters 8 and 9

### ISSUE THREAD

**Issue by Vrabbers** [hpi-swa-lab/SqueakByExample-english#100]
In section 8.1, page 178, the explanation for the code snippet mentions `Object>>deepCopy:`, but its snippet uses `veryDeepCopy`.
![image](https://user-images.githubusercontent.com/25323861/108413882-536fb000-720a-11eb-8c25-a0319def14b8.png)

In the very end of 9.6, page 214, the code snippet provided for `anySatisfy:` and `gather:` are the same.
![image](https://user-images.githubusercontent.com/25323861/108414304-d4c74280-720a-11eb-804a-cb0786119449.png)

**Comment by LinqLover** [comment]
Thanks a lot for filing these issues, @Vrabbers!

## Proposed solutions

- For the deep copying, I think the text is wrong. Iirc `#deepCopy` has no cycle protection whereas `#veryDeepCopy` has?

- For `#gather:`, I would propose the following example instead:
  ```smalltalk
  colors gather: [:color | color names] --> #(#white #snow #yellow #lemon #red #maraschino #blue #blueberry #orange)
  ```

@codeZeilen If you agree with these proposals, I'll be glad to submit a PR. :-)

**Comment by LinqLover** [comment]
@codeZeilen Please reply with a comment for approval in the future, I missed that because GitHub doesn't notify me about reactions 😅
