### ISSUE TITLE
Getting rid of all the pre-releases

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-lab/SqueakByExample-english#118]
But how? @LinqLover  :D

**Comment by LinqLover** [comment]
Should be simple similar to https://github.com/hpi-swa-lab/SqueakByExample-english/pull/104#issuecomment-827118574. I can do this. :-)

But the question is: Do we want to change our pre-release strategy? For development, it would be helpful if we could always see a few of the latest PDF files in the repository. GitHub Actions artifacts are always zipped which would make that less convenient. Another problem with the status quo is that for pull requests, this option is not available.

Should we maybe add a small workflow script that automatically deletes all but the <var>n</var> latest release artifacts? Or should we just commit the built PDFs to another branch (which we even could deploy to GitHub Pages if we wanted)? Then we could maintain one file per branch (and we could use `git push -f` to avoid storing the old files in the repository). Or we could try to return to the Google Drive uploads.

Independently of this proposal, if you confirm, I will remove all pre-releases right now so we can remove pressure on the GitHub storage limits. :-)

**Comment by LinqLover** [comment]
All older prereleases have now been deleted by the new CI job (and will continue being housekeeped in the future).
