### ISSUE TITLE
New content: Advanced debugging tools

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-lab/SqueakByExample-english#122]
- summary of debugger entry points: breakpoint/error, debug it, interrupt, process browser (`Process>>#debug`)
- `#haltIf:`, `#haltOnce`
- `#inspectOnce`
- breakpoints (CodeHolder menu)
- Debugger menus: Return entered value, run to selection, run until

**Comment by LinqLover** [comment]
add index for halt

**Comment by LinqLover** [comment]
add index for breakpoint

**Comment by LinqLover** [comment]
- at the end of section on debugger (6.5), add paragraph on haltIf, haltOnce, breakpints
- at the end of section, mention menus
- mention process browser in "There are a few other ways to get into the debugger"

**Comment by codeZeilen** [comment]
- [ ] at the end of section on debugger (6.5), add paragraph on haltIf, haltOnce, breakpints
- [ ] at the end of section, mention menus
- [ ] mention process browser in "There are a few other ways to get into the debugger"
- [ ] add index for breakpoint/halt
