### ISSUE TITLE
Optimize 3-column figure alignment in Quick Tour chapter

### ISSUE THREAD

**Issue by tom95** [hpi-swa-lab/SqueakByExample-english#13]
See @LinqLover 's comment here: https://github.com/codeZeilen/SqueakByExample-english/commit/b2eefcff34e8cd032daf423fe2915959272c281b#commitcomment-35638342

**Comment by LinqLover** [comment]
Ah, finally we have got an issue tracker for this project! :+1:

**Comment by LinqLover** [comment]
Closing this because it looks okay in my view since 5a8cd89.
![image](https://user-images.githubusercontent.com/38782922/94483037-8a511500-01da-11eb-982e-8b4e6bc14be5.png)
@codeZeilen Please reopen if you think this still needs improvement
