### ISSUE TITLE
Simplify path for readers to load the SmalltalkSources?

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-lab/SqueakByExample-english#141]
It's a great benefit that all methods in the book are actually available in a working package here in this repo. However, as a naive reader, I was not able to find any hint in the book on how to get these sources. Why not provide an easy way for readers to get these sources?

Possible options:

- Provide a Metacello script that loads the latest SmalltalkSources from the repo (that could refer to the right branch). This could be mentioned right in the preface ("Examples and exercises") and perhaps be backreferenced from the beginning of Chapter 2 and maybe Chapter 11 as well as from the FAQ
- Automatically deploy the sources to a repo on SqueakSource, and describe in the book how this repo can be accessed. Con: Especially for the first chapters, readers might feel overwhelmed by these instructions.

**Comment by LinqLover** [comment]
Oh, I just noticed the mention of http://www.squeaksource.com/QuintoExampleSBE.html which is out of date. This is not good :D

**Comment by LinqLover** [comment]
@codeZeilen And later the book also mentions http://squeaksource.com/SqueakByExample which is out of date ... Should we keep it updated or use a fictive URL instead? If the former, for which version of the book, and manually or via CI? :-)

![image](https://github.com/hpi-swa-lab/SqueakByExample-english/assets/38782922/3a34a85e-6e8e-4380-ad08-153a09f1a1c8)
![image](https://github.com/hpi-swa-lab/SqueakByExample-english/assets/38782922/fb79a231-ac1b-4adc-b4d3-d7487c1e23c7)

**Comment by LinqLover** [comment]
What license?

![image](https://github.com/hpi-swa-lab/SqueakByExample-english/assets/38782922/750f449a-2718-43a2-bc1e-49203c0b906c)

**Comment by codeZeilen** [comment]
@LinqLover yes, maybe mention license in the repo description instead
