### ISSUE TITLE
Figure 1.2 does not show the world main docking bar

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-lab/SqueakByExample-english#198]
However, the text below it mentions it.

**Comment by codeZeilen** [comment]
@LinqLover Is that a minor thing? From looking at the script of the figure, I was not able to figure out why it is missing. You can point me to the fix and I'll take care of it.

**Comment by LinqLover** [comment]
@codeZeilen Please see #201. We hide the docking bar by default so it has to be explicitly added, similar to /figures/Tools.png.
