### ISSUE TITLE
Test 247 in 5.3 broken

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-lab/SqueakByExample-english#44]
@LinqLover  That one is on me, tried to improve the formatting of the listing and broke the test...

**Comment by LinqLover** [comment]
I cannot reproduce this on the master. Are you referring to this?

https://github.com/hpi-swa-lab/SqueakByExample-english/pull/43/files#diff-989f869bad5af04acb0996d98ee3c0ad93283bd2a45152981e913cccef96e74bR123

**Comment by LinqLover** [comment]
Nevermind, I was on the wrong branch. Why didn't the CI prevent you from merging that change?
