### ISSUE TITLE
Chapter on WebClient

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-lab/SqueakByExample-english#49]
I think that would be quite useful :)

**Comment by LinqLover** [comment]
Is this worth an own chapter or would this be part of #50?

**Comment by codeZeilen** [comment]
Hm... I am thinking writing it as its own chapter, maybe in combination with other networking features, depending on the amount of available material. :)

**Comment by LinqLover** [comment]
There is already a pretty expensive tutorial on WebClient and WebServer in the Help Browser. Personally, I found it very helpful. We could reuse some content from there or also just reference to this in-image resource.

**Comment by LinqLover** [comment]
Only a FAQ that mentions the tutorial in-image, maybe later a chapter
