### ISSUE TITLE
[Proofreading] Chapter 11: Morphic - Style and Formatting

### ISSUE THREAD

**Issue by phoeinx** [hpi-swa-lab/SqueakByExample-english#67]
I am proofreading Chapter 11: Morphic and am using the SWA20/21 image as my test image. (https://www.hpi.uni-potsdam.de/hirschfeld/artefacts/lecture-image/SWA2021.zip)

**Style / Formatting:**

- _S1. Page 223_
    - <img width="528" alt="image" src="https://user-images.githubusercontent.com/34538290/97691410-9e6c8880-1a9e-11eb-9ed8-e1982cb98111.png">
     - if _down_ is printed in italic, _right_ should also be printed in italics
- _S2. Page 223_
    - <img width="549" alt="image" src="https://user-images.githubusercontent.com/34538290/97691558-ccea6380-1a9e-11eb-972f-75a0327a76b2.png">
    - two points is one to many :D 
- _S3. Missing points after figure descriptions._
    - Class 11.2
    - Class 11.20
    - Class 11.24
    - Class 11.27
- _S4. Method information in figure descriptions_
     - <img width="526" alt="image" src="https://user-images.githubusercontent.com/34538290/97692338-f1930b00-1a9f-11eb-886f-c439ecf55831.png">
    - when named directly, as far as I can see, every method but horizontalBar and verticalBar have been identified with their Class in front like : SBECrossMorph>>drawOn:
- _S5. Space before return value_
    - as the space before return value is used as a convention in the other examples those few with out it don't fit
    - Method 11.12
    - Method 11.14
    - Methods 11.31
- _S6. Exercises vs. only code descriptions_
    - not really a problem but it feels kind of inconsistent
    - some provided code snippets come with a request to define / update etc. them oneself (identified by a squeak cat head before them). (E.g. Method 11.4) Others come with an description and saying how things can be done. (E.g. Method 11.5). I suppose the ones without an exercise aren't really necessary to follow the tutorial? But as this chapter feels like a - try every example - tutorial this for me personally just appeared a bit inconsistent.
- _S7. Copy problems_
    - When copying the code snippet on page 232 (11.17) what appears like a single dash turns out to be two dashes, thus leading to debugging in Squeak instead of just being able to run the code 
    - <img width="213" alt="image" src="https://user-images.githubusercontent.com/34538290/97693579-ac6fd880-1aa1-11eb-93e6-02632628e5fe.png">
    -  "keyValue = $-- asciiValue" 
- _S8. Example abstraction levels_
    - On page 244 Figure 11.6 provides an abstract explanation giving the method that one can use to get an Input Dialog, Figure 11.7 on the other hand provides a code sample which can be used directly.
    - <img width="556" alt="image" src="https://user-images.githubusercontent.com/34538290/97693665-ca3d3d80-1aa1-11eb-8ef4-526adc76d92f.png">
- _S9. Parameter Names_
    - Method 11.23 is the only place where an incoming event parameter is named _ev_ and not _anEvent_
    - <img width="531" alt="image" src="https://user-images.githubusercontent.com/34538290/97693925-2902b700-1aa2-11eb-972a-049023c12c63.png">
- _S10. Not using accessor methods_
    - In Method 11.29 instance variables are set directly and not via accessor methods, which especially for faces: and dieValue: is weird, because we define those methods later on (and they do sensible sanity checks)
    - <img width="536" alt="image" src="https://user-images.githubusercontent.com/34538290/97694075-6404ea80-1aa2-11eb-9bd0-9dd2f602c9cb.png">

**Comment by codeZeilen** [comment]
### Unsolved and migrated to a new issue afterwards:

> S6. Exercises vs. only code descriptions
> 
>     not really a problem but it feels kind of inconsistent
>     some provided code snippets come with a request to define / update etc. them oneself (identified by a squeak cat head before them). (E.g. Method 11.4) Others come with an description and saying how things can be done. (E.g. Method 11.5). I suppose the ones without an exercise aren't really necessary to follow the tutorial? But as this chapter feels like a - try every example - tutorial this for me personally just appeared a bit inconsistent.

> S10. Not using accessor methods
> 
>     In Method 11.29 instance variables are set directly and not via accessor methods, which especially for faces: and dieValue: is weird, because we define those methods later on (and they do sensible sanity checks)
