### ISSUE TITLE
[Proofreading] Chapter 11: Morphic - Content Clarity and General

### ISSUE THREAD

**Issue by phoeinx** [hpi-swa-lab/SqueakByExample-english#68]
I am proofreading Chapter 11: Morphic and am using the SWA20/21 image as my test image. (https://www.hpi.uni-potsdam.de/hirschfeld/artefacts/lecture-image/SWA2021.zip)

**Content Clarity:**
- _C1.Page 222_
     - "You can create a morph to represent any object, although how good a representation you get depends on the object!" -        
     - Mhm, here I was wondering if this statement meant the inherent characteristics of the object or the _asMorph_ implementation of the class of said object.
- _C2.Page 223_
     - "The position method returns a Point that describes the location of the morph’s upper left corner (or the upper left corner of its bounding box). "
               - <img width="600" alt="image" src="https://user-images.githubusercontent.com/34538290/97632267-92e37800-1a32-11eb-9f37-f490eacb4f3c.png">
               - the or is kind of confusing because it might imply two alternatives when _position_ actually always returns the upper left corner of the bounding box of a Morph. Maybe just say it returns the upper left corner of its bounding box to be precise?
- _C3. Chapter summary_
    - "You can compose morphs by embedding one onto another, either by drag and drop or by sending the message addMorph:." 
    - Would rather be something like: "either by using the 'embed into' option, implementing an embedding drag and drop behaviour or by sending the message addMorph:"
- _C4. Chapter summary2_
     - a last bullet point about Canvases would be nice I think :)
       
**General:**
- _G1. yellow / blue / red clicking_
     - I am not sure if I might be touching on some treasured conventions here, but I think readability for beginners would be improved by referring to yellow, red and blue clicking by left, right and "option" clicking. 
         - <img width="155" alt="image" src="https://user-images.githubusercontent.com/34538290/97689803-682e0980-1a9c-11eb-909f-4229c81baafe.png">
         - not everyone has a mouse like that :D

**Comment by LinqLover** [comment]
> G1. yellow/blue/red clicking

Unfortunately, it depends on your host system and VM settings how the buttons are mapped to the mouse device :/ See [FAQ: MouseButtons](https://wiki.squeak.org/squeak/897) for more information. I guess this is a necessary abstraction indeed ...
