### ISSUE TITLE
Getting the 5.3 release ready

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-lab/SqueakByExample-english#74]
- [x] Deactivate shadows for screenshots, as some now have shadows and some do not
- [x] Set rounded corners for windows
- [x] Rename "First Application" some something that is more fitting with regard to Squeak
- [x] Improve consistency of listings
- [x] Check for consistent code style (e.g. no whitespace at beginning and end of block)
- [x]  Add a list of contributors somewhere at the front of the book :)
- [x] Finish last review of chapters
- [x] SortFunctions (#88)
- [x] Get ISBN

**Comment by LinqLover** [comment]
> - [] Deactivate shadows for screenshots, as some now have shadows and some do not
> - [] Set rounded corners for windows

These should all be configurable in https://github.com/hpi-swa-lab/SqueakByExample-english/blob/master/SmalltalkSources/SBE-Extract.package/SBEWorldHelper.class/instance/useScreenshotPreferencesDuring..st. Shall I do this?

**Comment by LinqLover** [comment]
What is the deadline?

**Comment by codeZeilen** [comment]
> These should all be configurable in https://github.com/hpi-swa-lab/SqueakByExample-english/blob/master/SmalltalkSources/SBE-Extract.package/SBEWorldHelper.class/instance/useScreenshotPreferencesDuring..st. Shall I do this?

That would be nice!

> What is the deadline?

End of November, so a release on the 4th of December becomes possible.

**Comment by LinqLover** [comment]
Alright, see #75. :-)

**Comment by codeZeilen** [comment]
Work on this continues in the branch `edition-5-3`
