### ISSUE TITLE
Some figures show decompile source

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-lab/SqueakByExample-english#76]
For example:
 - 6.6
 - 6.7
 - 6.30
 - 6.31

**Comment by LinqLover** [comment]
@codeZeilen Can you explain a bit more in detail what you are referring to? I checked all the figures you mentioned generated by the latest cron build (4 days ago) both for 5.3 and 6.0 Alpha, but they look fine to me in the sense that the "What to show" button (if visible) is labelled "source" and the displayed source code contains the correct temporary variable names (not any `t1` names, etc.). Are you referring to another build, or are you having problems to run the figure generation locally?

**Comment by codeZeilen** [comment]
The moment I saw your reply, even before reading it, I realized that it was my local build, so we are good here :)
