### ISSUE TITLE
Find a source for Black's Rule of Testing

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-lab/SqueakByExample-english#89]
Or remove the naming

**Comment by LinqLover** [comment]
What about this?

Julien Delplanque, Stéphane Ducasse, Guillermo Polito, Andrew Black, Anne Etien. Rotten Green Tests. ICSE 2019 - International Conference on Software Engineering, May 2019, Montréal, Canada. ffhal-02002346v2f
https://hal.inria.fr/hal-02002346/document

> A green (passing) test is usually taken as a robust sign that the code under test is valid. However, some green tests contain assertions that are never executed. We call such tests _Rotten Green Tests_.

Hm ... the paragraph in the book sounds like a misinterpretation of this paper. But it's the only publication of Andrew P. Black about testing that I could find ...

**Comment by LinqLover** [comment]
@codeZeilen As there seems no proper source, can I just rename this item to?

- One test per property.

**Comment by LinqLover** [comment]
ack
