### ISSUE TITLE
Update index and bibliography as part of CI

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-lab/SqueakByExample-english#91]
> This apparently has been forgotten for a very long time. Shall I move this into another PR? Do we need this at all, or can this file be deleted? Or should I spend some time automating the update of this file via CI? :-)

_Originally posted by @LinqLover in https://github.com/hpi-swa-lab/SqueakByExample-english/pull/88#discussion_r541755870_

> yeah that should probably be part of the CI o.O But no hurry!

_Originally posted by @codeZeilen in https://github.com/hpi-swa-lab/SqueakByExample-english/pull/88#discussion_r542219347_

**Comment by codeZeilen** [comment]
The updating of the index is already part of CI in the edition-5-3 branch. I haven't had time to move it to master yet.

**Comment by LinqLover** [comment]
This has already been solved via 49452601d5dcaca6bae0febacfea1dedb3d40c8f.
